# Generated by Django 5.0.1 on 2024-02-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GETapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='model',
            table='helo',
        ),
    ]
